title : Shaggys Dope Blog
tagline: Home For My Random Thoughts
author :
  name : Shaggy TwoDope
  email : twodopeshaggy@gmail.com
  github : twodopeshaggy
  twitter : shaggy_twodope
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - bash.md
  - categories.html
  - pages.html
  - about.md
  
